accounts:
  - name: alice
    coins: ["2000000000token", "200000000stake"]
    mnemonic: "wine rich chunk that swim afford found auction travel dentist razor furnace fluid hidden happy enroll pilot dragon market broom bus merry salad assume"
  - name: bob
    coins: ["10000token", "100000000stake"]
    mnemonic: "major spatial spoil earn capable receive tourist bronze call coral mango betray demand size certain strike decline pluck baby eight maple pyramid cage cabbage"
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
init:
  home: "./.testnet"
genesis:
  app_state:
    alliance:
      assets:
        - denom: 'uluna'
          reward_weight: "0.5"
          take_rate: "0.5"
        - denom: 'bluna'
          reward_weight: "0.9"
          take_rate: "0.9"
        - denom: 'token'
          reward_weight: "5"
          take_rate: "0.9"
      params: 
        reward_delay_time: "60s"
        reward_claim_interval: "10s"