version: "3"

services:
  alliance_node:
    container_name: alliance_node
    image: "terra-money/localnet-allianced"
    environment:
      - DEBUG=1
      - ID=0
      - LOG=${LOG:-allianced.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    volumes:
      - ./.testnets:/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.5.20

  alliance_node_1:
    container_name: alliance_node_1
    image: "terra-money/localnet-allianced"
    environment:
      - DEBUG=0
      - ID=1
      - LOG=${LOG:-allianced.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
      - "2346:2345"
    volumes:
      - ./.testnets:/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.5.21

  alliance_node_2:
    container_name: alliance_node_2
    image: "terra-money/localnet-allianced"
    environment:
      - DEBUG=0
      - ID=2
      - LOG=${LOG:-allianced.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
      - "2347:2345"
    volumes:
      - ./.testnets:/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.5.22

  alliance_node_3:
    container_name: alliance_node_3
    image: "terra-money/localnet-allianced"
    environment:
      - DEBUG=0
      - ID=3
      - LOG=${LOG:-allianced.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
      - "2348:2345"
    volumes:
      - ./.testnets:/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.5.23

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/25